version: 2

jobs:
  build:
    docker:
      - image: cimg/node:10.24.1
    steps:
      - checkout
      - run: npm install
      - run: npm install

  cat_readme:
    docker:
      - image: cimg/node:10.24.1

    steps:
      - checkout
      - run: cat README.md

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          requires:
            - cat_readme
      - cat_readme:
          type: approval




